"use client";

import { FileSpreadsheet, Printer, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";

type Row = { id: number; client: string; clientNumber: string | null; branch: string; accountOfficer: string; type: string; subject: string | null; notes: string; visitAt: string };

export function DashboardClientLogs({ rows, canDelete = false }: { rows: Row[]; canDelete?: boolean }) {
  const router = useRouter();
  const [deletingId, setDeletingId] = useState<number | null>(null);
  const [error, setError] = useState<string | null>(null);
  const cell = (value: unknown) => `"${String(value ?? "").replace(/"/g, '""')}"`;
  function excel() { const csv = [["Date", "Client", "Client No.", "Branch", "Account Officer", "Type", "Subject", "Notes"], ...rows.map((r) => [r.visitAt, r.client, r.clientNumber, r.branch, r.accountOfficer, r.type, r.subject, r.notes])].map((r) => r.map(cell).join(",")).join("\r\n"); const url = URL.createObjectURL(new Blob(["\ufeff", csv], { type: "text/csv;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = "client-logs.csv"; a.click(); setTimeout(() => URL.revokeObjectURL(url), 500); }
  async function remove(row: Row) { if (!window.confirm(`Delete the client log for ${row.client}? This cannot be undone.`)) return; setDeletingId(row.id); setError(null); try { const response = await fetch(`/api/client-logs/${row.id}`, { method: "DELETE" }); const data = await response.json().catch(() => null); if (!response.ok) throw new Error(data?.error ?? "Unable to delete client log."); router.refresh(); } catch (error) { setError(error instanceof Error ? error.message : "Unable to delete client log."); } finally { setDeletingId(null); } }
  return <div className="space-y-3">{error ? <div className="rounded-md border border-red-200 bg-red-50 px-3 py-2 text-sm font-semibold text-red-700">{error}</div> : null}<div className="flex justify-end gap-2 print:hidden"><button className="btn-secondary px-3 py-1.5 text-xs" onClick={() => window.print()}><Printer className="h-4 w-4" />Print</button><button className="btn-secondary px-3 py-1.5 text-xs" onClick={excel}><FileSpreadsheet className="h-4 w-4" />Excel</button></div><div className="panel max-h-[480px] overflow-auto"><table className="w-full min-w-[1000px] text-xs"><thead className="sticky top-0 bg-slate-50"><tr><th className="px-3 py-2 text-left">Date</th><th className="px-3 py-2 text-left">Client</th><th className="px-3 py-2 text-left">Branch</th><th className="px-3 py-2 text-left">Account Officer</th><th className="px-3 py-2 text-left">Type</th><th className="px-3 py-2 text-left">Activity</th>{canDelete ? <th className="px-3 py-2 text-right print:hidden">Action</th> : null}</tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-t border-slate-100"><td className="whitespace-nowrap px-3 py-2">{new Date(row.visitAt).toLocaleString("en-US")}</td><td className="px-3 py-2"><b>{row.client}</b><br /><span className="text-slate-500">{row.clientNumber ?? "-"}</span></td><td className="px-3 py-2">{row.branch}</td><td className="px-3 py-2">{row.accountOfficer}</td><td className="px-3 py-2">{row.type.replace(/_/g, " ")}</td><td className="px-3 py-2"><b>{row.subject}</b>{row.subject ? <br /> : null}{row.notes}</td>{canDelete ? <td className="px-3 py-2 text-right print:hidden"><button type="button" className="inline-flex items-center gap-1 rounded-md border border-red-200 px-2 py-1 font-semibold text-red-600 hover:bg-red-50 disabled:opacity-50" onClick={() => remove(row)} disabled={deletingId === row.id}><Trash2 className="h-3.5 w-3.5" />{deletingId === row.id ? "Deleting..." : "Delete"}</button></td> : null}</tr>)}{!rows.length ? <tr><td colSpan={canDelete ? 7 : 6} className="p-8 text-center text-slate-500">No client logs match the filters.</td></tr> : null}</tbody></table></div></div>;
}
