"use client";

import { FileSpreadsheet, Printer } from "lucide-react";

type Row = { id: number; client: string; clientNumber: string | null; branch: string; accountOfficer: string; type: string; subject: string | null; notes: string; visitAt: string };

export function DashboardClientLogs({ rows }: { rows: Row[] }) {
  const cell = (value: unknown) => `"${String(value ?? "").replace(/"/g, '""')}"`;
  function excel() { const csv = [["Date", "Client", "Client No.", "Branch", "Account Officer", "Type", "Subject", "Notes"], ...rows.map((r) => [r.visitAt, r.client, r.clientNumber, r.branch, r.accountOfficer, r.type, r.subject, r.notes])].map((r) => r.map(cell).join(",")).join("\r\n"); const url = URL.createObjectURL(new Blob(["\ufeff", csv], { type: "text/csv;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = "client-logs.csv"; a.click(); setTimeout(() => URL.revokeObjectURL(url), 500); }
  return <div className="space-y-3"><div className="flex justify-end gap-2 print:hidden"><button className="btn-secondary px-3 py-1.5 text-xs" onClick={() => window.print()}><Printer className="h-4 w-4" />Print</button><button className="btn-secondary px-3 py-1.5 text-xs" onClick={excel}><FileSpreadsheet className="h-4 w-4" />Excel</button></div><div className="panel max-h-[480px] overflow-auto"><table className="w-full min-w-[1000px] text-xs"><thead className="sticky top-0 bg-slate-50"><tr><th className="px-3 py-2 text-left">Date</th><th className="px-3 py-2 text-left">Client</th><th className="px-3 py-2 text-left">Branch</th><th className="px-3 py-2 text-left">Account Officer</th><th className="px-3 py-2 text-left">Type</th><th className="px-3 py-2 text-left">Activity</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-t border-slate-100"><td className="whitespace-nowrap px-3 py-2">{new Date(row.visitAt).toLocaleString("en-US")}</td><td className="px-3 py-2"><b>{row.client}</b><br /><span className="text-slate-500">{row.clientNumber ?? "-"}</span></td><td className="px-3 py-2">{row.branch}</td><td className="px-3 py-2">{row.accountOfficer}</td><td className="px-3 py-2">{row.type.replace(/_/g, " ")}</td><td className="px-3 py-2"><b>{row.subject}</b>{row.subject ? <br /> : null}{row.notes}</td></tr>)}{!rows.length ? <tr><td colSpan={6} className="p-8 text-center text-slate-500">No client logs match the filters.</td></tr> : null}</tbody></table></div></div>;
}
