// Generated by scripts/generate-change-log.ts - do not edit by hand.
// Regenerate with: npm run changelog:generate

import type { ChangeLogEntry } from "@/lib/change-log";

export const CHANGE_LOG: ChangeLogEntry[] = [
  {
    "number": 1,
    "date": "2026-06-26",
    "commit": "0c313a7",
    "title": "Initial ALC client inquiry system"
  },
  {
    "number": 2,
    "date": "2026-07-01",
    "commit": "f1ed2b9",
    "title": "Update sync, inquiry, loan, and user management"
  },
  {
    "number": 3,
    "date": "2026-07-13",
    "commit": "75e05f2",
    "title": "Add loan monitoring and remedial workflows"
  },
  {
    "number": 4,
    "date": "2026-07-14",
    "commit": "b7d1f09",
    "title": "Refine remedial filtering and pagination"
  },
  {
    "number": 5,
    "date": "2026-07-16",
    "commit": "f590146",
    "title": "Add account tagging and loan product reporting"
  },
  {
    "number": 6,
    "date": "2026-07-23",
    "commit": "0bd5c80",
    "title": "Add payment posting and account tagging updates"
  },
  {
    "number": 7,
    "date": "2026-07-23",
    "commit": "b3e6069",
    "title": "Add division tagging to account tagging"
  },
  {
    "number": 8,
    "date": "2026-07-24",
    "commit": "45c6c8c",
    "title": "Add account tagging locations and Area TL user creation"
  },
  {
    "number": 9,
    "date": "2026-07-24",
    "commit": "cafeb95",
    "title": "Add AO tagging reports and condition approvals"
  },
  {
    "number": 10,
    "date": "2026-07-24",
    "commit": "d45d48d",
    "title": "Improve AO assignment summary cards"
  },
  {
    "number": 11,
    "date": "2026-07-24",
    "commit": "64447a7",
    "title": "Break down AO cards by assignment zone"
  },
  {
    "number": 12,
    "date": "2026-07-24",
    "commit": "1ccedb3",
    "title": "Restrict Account Officer access and views"
  },
  {
    "number": 13,
    "date": "2026-07-24",
    "commit": "7599549",
    "title": "Add AO distribution and Area TL assignment controls"
  },
  {
    "number": 14,
    "date": "2026-07-24",
    "commit": "f6f0158",
    "title": "Align AO totals with zone breakdown"
  },
  {
    "number": 15,
    "date": "2026-07-24",
    "commit": "1925287",
    "title": "Enlarge AO distribution chart and show unassigned accounts"
  },
  {
    "number": 16,
    "date": "2026-07-24",
    "commit": "2c13029",
    "title": "Show percentages inside AO chart slices"
  },
  {
    "number": 17,
    "date": "2026-07-24",
    "commit": "b6b841c",
    "title": "Add customer and principal metrics to AO chart legend"
  },
  {
    "number": 18,
    "date": "2026-07-24",
    "commit": "3ae6ad9",
    "title": "Add province account distribution chart"
  },
  {
    "number": 19,
    "date": "2026-07-24",
    "commit": "b3d2c40",
    "title": "Add customer condition to bulk assignment"
  },
  {
    "number": 20,
    "date": "2026-07-24",
    "commit": "b582747",
    "title": "Exclude conditioned customers from account tagging search"
  },
  {
    "number": 21,
    "date": "2026-07-24",
    "commit": "294f24f",
    "title": "Add client condition management module"
  },
  {
    "number": 22,
    "date": "2026-07-27",
    "commit": "49314cc",
    "title": "Add loan charges and flexible account tagging"
  },
  {
    "number": 23,
    "date": "2026-07-27",
    "commit": "74032b1",
    "title": "Fix account tagging table header visibility"
  },
  {
    "number": 24,
    "date": "2026-07-27",
    "commit": "2685984",
    "title": "Remove Branch AO from bulk assignment"
  },
  {
    "number": 25,
    "date": "2026-07-27",
    "commit": "8edc6e6",
    "title": "Exclude employee loans from account tagging"
  },
  {
    "number": 26,
    "date": "2026-07-27",
    "commit": "04f7a5e",
    "title": "Synchronize customer condition options across views"
  },
  {
    "number": 27,
    "date": "2026-07-27",
    "commit": "090655f",
    "title": "Restore account officer bulk assignment"
  },
  {
    "number": 28,
    "date": "2026-07-27",
    "commit": "810df79",
    "title": "Populate assignment locations from PSGC addresses"
  },
  {
    "number": 29,
    "date": "2026-07-27",
    "commit": "2299f42",
    "title": "Use PSGC codes for barangay hierarchy"
  },
  {
    "number": 30,
    "date": "2026-07-27",
    "commit": "ec55dd0",
    "title": "Tighten PSGC barangay address matching"
  },
  {
    "number": 31,
    "date": "2026-07-27",
    "commit": "85594ef",
    "title": "Move tagging location columns beside address"
  },
  {
    "number": 32,
    "date": "2026-07-27",
    "commit": "9d23dfa",
    "title": "Load eligible accounts on empty tagging search"
  },
  {
    "number": 33,
    "date": "2026-07-27",
    "commit": "e3cefe7",
    "title": "Add account location report"
  },
  {
    "number": 34,
    "date": "2026-07-27",
    "commit": "a6e247f",
    "title": "Add hierarchical location report drill-down"
  },
  {
    "number": 35,
    "date": "2026-07-28",
    "commit": "a2bd03e",
    "title": "Merge location names case-insensitively"
  },
  {
    "number": 36,
    "date": "2026-07-28",
    "commit": "35a16bb",
    "title": "Add inline location correction to report"
  },
  {
    "number": 37,
    "date": "2026-07-28",
    "commit": "22b0046",
    "title": "Move report address after principal balance"
  },
  {
    "number": 38,
    "date": "2026-07-29",
    "commit": "dd5fb50",
    "title": "Allow location tagging without account officer"
  },
  {
    "number": 39,
    "date": "2026-07-29",
    "commit": "c0b4a8d",
    "title": "Add search to location report results"
  },
  {
    "number": 40,
    "date": "2026-07-30",
    "commit": "4398837",
    "title": "Add filtered bulk location updates"
  },
  {
    "number": 41,
    "date": "2026-07-30",
    "commit": "0bd45e6",
    "title": "Add location masterlist and pivot hierarchy"
  },
  {
    "number": 42,
    "date": "2026-07-30",
    "commit": "1ed90f9",
    "title": "Link loan metrics to location masterlist"
  },
  {
    "number": 43,
    "date": "2026-07-30",
    "commit": "155f9a3",
    "title": "Add account officer barangay breakdown"
  },
  {
    "number": 44,
    "date": "2026-07-30",
    "commit": "4a5188f",
    "title": "Add location account officer summaries"
  },
  {
    "number": 45,
    "date": "2026-07-30",
    "commit": "54dbca6",
    "title": "Add location client drilldowns"
  },
  {
    "number": 46,
    "date": "2026-07-30",
    "commit": "c5a19f7",
    "title": "Add assigned officer client counts"
  },
  {
    "number": 47,
    "date": "2026-07-30",
    "commit": "062f181",
    "title": "Remove location client hover summaries"
  },
  {
    "number": 48,
    "date": "2026-07-30",
    "commit": "750ab59",
    "title": "Remove clickable location client counts"
  },
  {
    "number": 49,
    "date": "2026-07-30",
    "commit": "4c4127b",
    "title": "Add global action progress bar"
  },
  {
    "number": 50,
    "date": "2026-07-30",
    "commit": "4474f1e",
    "title": "Use principal balance for location portfolio"
  },
  {
    "number": 51,
    "date": "2026-07-30",
    "commit": "dbe8ea0",
    "title": "Add persistent loan location linking"
  },
  {
    "number": 52,
    "date": "2026-07-30",
    "commit": "af84fa3",
    "title": "Add account officer location pivot"
  },
  {
    "number": 53,
    "date": "2026-07-30",
    "commit": "be68e4f",
    "title": "Deduplicate location pivot totals"
  },
  {
    "number": 54,
    "date": "2026-07-30",
    "commit": "d3eb6fc",
    "title": "Add paginated officer barangay loan reports"
  },
  {
    "number": 55,
    "date": "2026-07-30",
    "commit": "f289c1d",
    "title": "Add location barangay loan reports"
  },
  {
    "number": 56,
    "date": "2026-07-30",
    "commit": "81f00e2",
    "title": "Highlight selected location hierarchy rows"
  },
  {
    "number": 57,
    "date": "2026-07-30",
    "commit": "04b776d",
    "title": "Modernize centered progress indicator"
  },
  {
    "number": 58,
    "date": "2026-07-30",
    "commit": "28cb10b",
    "title": "Prevent excessive address search joins"
  },
  {
    "number": 59,
    "date": "2026-07-30",
    "commit": "deb2fa9",
    "title": "Consolidate account tagging client filters"
  },
  {
    "number": 60,
    "date": "2026-07-30",
    "commit": "9adbf58",
    "title": "Show progress for all application actions"
  },
  {
    "number": 61,
    "date": "2026-07-31",
    "commit": "fd1603c",
    "title": "Add account officer summary modal exports"
  },
  {
    "number": 62,
    "date": "2026-07-31",
    "commit": "15fae26",
    "title": "Calculate location loan aging from due dates"
  },
  {
    "number": 63,
    "date": "2026-07-31",
    "commit": "c443f5a",
    "title": "Fix stale navigation progress overlay"
  },
  {
    "number": 64,
    "date": "2026-07-31",
    "commit": "fda9824",
    "title": "Optimize location aging calculations"
  },
  {
    "number": 65,
    "date": "2026-07-31",
    "commit": "39e4e79",
    "title": "Add drilldown reports to location client counts"
  },
  {
    "number": 66,
    "date": "2026-07-31",
    "commit": "3941e62",
    "title": "Make location aging totals client-consistent"
  },
  {
    "number": 67,
    "date": "2026-07-31",
    "commit": "e517a92",
    "title": "Add nested officer status drilldowns"
  },
  {
    "number": 68,
    "date": "2026-07-31",
    "commit": "25e7c74",
    "title": "Add unlinked loan assignment manager"
  },
  {
    "number": 69,
    "date": "2026-07-31",
    "commit": "bd22535",
    "title": "Group account officers by area team leader"
  },
  {
    "number": 70,
    "date": "2026-07-31",
    "commit": "d6f2d5a",
    "title": "Add loan officer reassignment controls"
  },
  {
    "number": 71,
    "date": "2026-08-05",
    "commit": "8ba43aa",
    "title": "Add past-due drilldown, sticky headers, wider report modals, and zero-value display cleanup"
  },
  {
    "number": 72,
    "date": "2026-08-06",
    "commit": "5b278e8",
    "title": "Add real loan type and payment transaction detail to the loan popup"
  },
  {
    "number": 73,
    "date": "2026-08-06",
    "commit": "b7d8a13",
    "title": "Fix sticky table headers hiding the first row on page-scrolled tables"
  },
  {
    "number": 74,
    "date": "2026-08-06",
    "commit": "1697993",
    "title": "Remove sticky positioning from the location-masterlist grid headers"
  },
  {
    "number": 75,
    "date": "2026-08-06",
    "commit": "e928c04",
    "title": "Remove sticky positioning from all page-scrolled table headers"
  },
  {
    "number": 76,
    "date": "2026-08-06",
    "commit": "31955ae",
    "title": "Add temporary Verify Address tool for location-linking corrections"
  },
  {
    "number": 77,
    "date": "2026-08-06",
    "commit": "822d408",
    "title": "Sort location pivot rows by portfolio, largest first"
  },
  {
    "number": 78,
    "date": "2026-08-06",
    "commit": "b222330",
    "title": "Add per-branch loan summary for account officers in Location Pivot"
  },
  {
    "number": 79,
    "date": "2026-08-06",
    "commit": "86d20d7",
    "title": "Add a totals row to the officer branch summary popup"
  },
  {
    "number": 80,
    "date": "2026-08-06",
    "commit": "8e67706",
    "title": "Add client permanent address and delay the global progress overlay"
  },
  {
    "number": 81,
    "date": "2026-08-07",
    "commit": "b433988",
    "title": "Add Branch loan summary button to Location Pivot officer rows"
  },
  {
    "number": 82,
    "date": "2026-08-07",
    "commit": "27ffc67",
    "title": "Speed up client search expand and loan-list rendering"
  },
  {
    "number": 83,
    "date": "2026-08-10",
    "commit": "68d52a1",
    "title": "Restrict the processing overlay to left-menu navigation only"
  },
  {
    "number": 84,
    "date": "2026-08-10",
    "commit": "bbc9f64",
    "title": "Cascade Verify Address province/municipality/barangay suggestions"
  },
  {
    "number": 85,
    "date": "2026-08-10",
    "commit": "dae2e9d",
    "title": "Fix VPS backup pull after IP change"
  },
  {
    "number": 86,
    "date": "2026-08-10",
    "commit": "45d40d2",
    "title": "Limit progress overlay and clean zero metrics"
  },
  {
    "number": 87,
    "date": "2026-08-10",
    "commit": "47651f1",
    "title": "Add cascading permanent address selectors"
  },
  {
    "number": 88,
    "date": "2026-08-10",
    "commit": "b165645",
    "title": "Add assignment summaries and loan row numbers"
  },
  {
    "number": 89,
    "date": "2026-08-10",
    "commit": "eb23b1b",
    "title": "Add user position and base branch grouping"
  },
  {
    "number": 90,
    "date": "2026-08-10",
    "commit": "d572c65",
    "title": "Remove semantic search from navigation"
  },
  {
    "number": 91,
    "date": "2026-08-11",
    "commit": "abc4a77",
    "title": "Restrict payments and add self-service passwords"
  },
  {
    "number": 92,
    "date": "2026-08-11",
    "commit": "c824800",
    "title": "Add reusable privilege access matrix"
  },
  {
    "number": 93,
    "date": "2026-08-11",
    "commit": "a4dccbb",
    "title": "Refine settings privilege access matrix"
  },
  {
    "number": 94,
    "date": "2026-08-11",
    "commit": "a0c1b33",
    "title": "Show loan summaries before search"
  },
  {
    "number": 95,
    "date": "2026-08-12",
    "commit": "b05e841",
    "title": "Enforce assigned privileges for app access"
  },
  {
    "number": 96,
    "date": "2026-08-12",
    "commit": "67d4137",
    "title": "Require explicit search for loan result list"
  },
  {
    "number": 97,
    "date": "2026-08-12",
    "commit": "3495133",
    "title": "Require search text for loan detail results"
  },
  {
    "number": 98,
    "date": "2026-08-12",
    "commit": "4407775",
    "title": "Apply Agusan Lending corporate branding"
  },
  {
    "number": 99,
    "date": "2026-08-12",
    "commit": "747108d",
    "title": "Allow public branding assets on login"
  },
  {
    "number": 100,
    "date": "2026-08-12",
    "commit": "23455aa",
    "title": "Improve account tagging result table scrolling"
  },
  {
    "number": 101,
    "date": "2026-08-12",
    "commit": "36e6d92",
    "title": "Group navigation and add branded application footer"
  },
  {
    "number": 102,
    "date": "2026-08-12",
    "commit": "42ef15f",
    "title": "Simplify and reposition branded login form"
  },
  {
    "number": 103,
    "date": "2026-08-12",
    "commit": "180c8a4",
    "title": "Refine ALC Central navigation and shell layout"
  },
  {
    "number": 104,
    "date": "2026-08-12",
    "commit": "07a9d9f",
    "title": "Move login left and add branded footer"
  },
  {
    "number": 105,
    "date": "2026-08-12",
    "commit": "34790d5",
    "title": "Rename website to ALC Central System"
  },
  {
    "number": 106,
    "date": "2026-08-12",
    "commit": "5ea967c",
    "title": "Center login in clear wallpaper area"
  },
  {
    "number": 107,
    "date": "2026-08-12",
    "commit": "17f244e",
    "title": "Refine navigation toggles and footer branding"
  },
  {
    "number": 108,
    "date": "2026-08-12",
    "commit": "53fcece",
    "title": "Require clicks to open navigation groups"
  },
  {
    "number": 109,
    "date": "2026-08-12",
    "commit": "bd2a642",
    "title": "Center login card in full viewport"
  },
  {
    "number": 110,
    "date": "2026-08-12",
    "commit": "8769f2e",
    "title": "Refine sidebar branding and copyright footer"
  },
  {
    "number": 111,
    "date": "2026-08-12",
    "commit": "02b5661",
    "title": "Move company logo to right header"
  },
  {
    "number": 112,
    "date": "2026-08-12",
    "commit": "2440f26",
    "title": "Normalize province grouping and labels"
  },
  {
    "number": 113,
    "date": "2026-08-13",
    "commit": "6f0204e",
    "title": "Move login left and enlarge footer logo"
  },
  {
    "number": 114,
    "date": "2026-08-13",
    "commit": "c061af4",
    "title": "Add matrix scrolling and modernize header controls"
  },
  {
    "number": 115,
    "date": "2026-08-13",
    "commit": "0a42da7",
    "title": "Enhance access matrix controls and reports"
  },
  {
    "number": 116,
    "date": "2026-08-13",
    "commit": "ac5c057",
    "title": "Streamline sign-in card"
  },
  {
    "number": 117,
    "date": "2026-08-13",
    "commit": "2677d41",
    "title": "Lower login and simplify footer"
  },
  {
    "number": 118,
    "date": "2026-08-13",
    "commit": "c04b95a",
    "title": "Refine settings scrolling and audit navigation"
  },
  {
    "number": 119,
    "date": "2026-08-13",
    "commit": "b2de419",
    "title": "Add user activity audit logs and reports"
  },
  {
    "number": 120,
    "date": "2026-08-13",
    "commit": "22e9fd2",
    "title": "Add audit user and date filters"
  },
  {
    "number": 121,
    "date": "2026-08-13",
    "commit": "03b27e5",
    "title": "Reduce access matrix switch size"
  },
  {
    "number": 122,
    "date": "2026-08-13",
    "commit": "c02c65b",
    "title": "Move sync status and add dashboard client logs"
  },
  {
    "number": 123,
    "date": "2026-08-13",
    "commit": "43e6346",
    "title": "Apply role privilege templates by default"
  },
  {
    "number": 124,
    "date": "2026-08-13",
    "commit": "9ffb55c",
    "title": "Generalize privilege access resolution"
  },
  {
    "number": 125,
    "date": "2026-08-13",
    "commit": "287de49",
    "title": "Restrict settings management to administrators"
  },
  {
    "number": 126,
    "date": "2026-08-13",
    "commit": "5df5b53",
    "title": "Limit admin-only scope to user management"
  },
  {
    "number": 127,
    "date": "2026-08-13",
    "commit": "02e06ae",
    "title": "Allow administrators to reset user passwords"
  },
  {
    "number": 128,
    "date": "2026-08-13",
    "commit": "56947b2",
    "title": "Add user management scroll areas"
  },
  {
    "number": 129,
    "date": "2026-08-13",
    "commit": "4fbec9a",
    "title": "Use a single database-backed privilege selector"
  },
  {
    "number": 130,
    "date": "2026-08-13",
    "commit": "cca5a51",
    "title": "Enhance dashboard client log management"
  },
  {
    "number": 131,
    "date": "2026-08-13",
    "commit": "62f4535",
    "title": "Add dashboard overview and client log tabs"
  },
  {
    "number": 132,
    "date": "2026-08-13",
    "commit": "e1d2d2b",
    "title": "Scope account officer client logs"
  },
  {
    "number": 133,
    "date": "2026-08-13",
    "commit": "c9aec4e",
    "title": "Add live client log filtering and admin editing"
  },
  {
    "number": 134,
    "date": "2026-08-13",
    "commit": "d60d6fa",
    "title": "Require typed confirmation for client log deletion"
  },
  {
    "number": 135,
    "date": "2026-08-14",
    "commit": "56cd88c",
    "title": "Expand client inquiry filters and update footer credit"
  },
  {
    "number": 136,
    "date": "2026-08-14",
    "commit": "58ce016",
    "title": "Align client log customer search scope"
  },
  {
    "number": 137,
    "date": "2026-08-14",
    "commit": "bbb6b50",
    "title": "Match client log entry scope to inquiry"
  },
  {
    "number": 138,
    "date": "2026-08-14",
    "commit": "bde6aa4",
    "title": "Add filtered modal client log entry"
  },
  {
    "number": 139,
    "date": "2026-08-14",
    "commit": "fffb70d",
    "title": "Reorder client log filters"
  },
  {
    "number": 140,
    "date": "2026-08-14",
    "commit": "04fda3a",
    "title": "Simplify client log search filters"
  },
  {
    "number": 141,
    "date": "2026-08-14",
    "commit": "0802c3d",
    "title": "Add live compact client log search"
  },
  {
    "number": 142,
    "date": "2026-08-14",
    "commit": "70f2c15",
    "title": "Allow Area Team Leaders to create users"
  },
  {
    "number": 143,
    "date": "2026-08-18",
    "commit": "a4fe7a4",
    "title": "Add area management with Area Team Leader assignment"
  },
  {
    "number": 144,
    "date": "2026-08-18",
    "commit": "4125785",
    "title": "Add deploy rollback script and user list search"
  },
  {
    "number": 145,
    "date": "2026-08-18",
    "commit": "23acaf4",
    "title": "Mark rollback script executable"
  },
  {
    "number": 146,
    "date": "2026-08-18",
    "commit": "4197e05",
    "title": "Fix rollback dump check failing under pipefail"
  },
  {
    "number": 147,
    "date": "2026-08-19",
    "commit": "cf953af",
    "title": "Add Branch TL assignment and restricted Area TL branch access"
  },
  {
    "number": 148,
    "date": "2026-08-19",
    "commit": "098940c",
    "title": "Add user Branch TL, hide empty barangays, modal client log editing"
  },
  {
    "number": 149,
    "date": "2026-08-19",
    "commit": "c739508",
    "title": "Fit more client logs on the dashboard screen"
  },
  {
    "number": 150,
    "date": "2026-08-20",
    "commit": "fe2c2ac",
    "title": "Let admins delete a user who only holds remedial assignments"
  },
  {
    "number": 151,
    "date": "2026-08-20",
    "commit": "23064ee",
    "title": "Drop the Role column from the users table"
  },
  {
    "number": 152,
    "date": "2026-08-20",
    "commit": "70a0243",
    "title": "Sortable sticky headers and denser layout for user and officer lists"
  },
  {
    "number": 153,
    "date": "2026-08-20",
    "commit": "ee4de56",
    "title": "Tie the team leader fields to the user's privilege"
  },
  {
    "number": 154,
    "date": "2026-08-20",
    "commit": "40e8958",
    "title": "Separate admin accounts and widen the audit trail"
  },
  {
    "number": 155,
    "date": "2026-08-20",
    "commit": "b0be4b4",
    "title": "Rebuild the officer pivot around team leaders, and sort the summaries"
  },
  {
    "number": 156,
    "date": "2026-08-20",
    "commit": "87b1ee7",
    "title": "Open a district to its officers, and drop the Area TL summary"
  },
  {
    "number": 157,
    "date": "2026-08-20",
    "commit": "47a763a",
    "title": "Client log popups, an officer schedule calendar, and a period filter"
  },
  {
    "number": 158,
    "date": "2026-08-24",
    "commit": "dc06288",
    "title": "Let each pivot level be arranged by dragging, per account"
  },
  {
    "number": 159,
    "date": "2026-08-24",
    "commit": "98da735",
    "title": "Add collection maps, reporting, and security hardening"
  },
  {
    "number": 160,
    "date": "2026-08-25",
    "commit": "aea0fae",
    "title": "Add guided new-loan assignment and user codes"
  },
  {
    "number": 161,
    "date": "2026-08-25",
    "commit": "b943f69",
    "title": "Clarify new-loan assignment row grouping"
  },
  {
    "number": 162,
    "date": "2026-08-25",
    "commit": "b7e284f",
    "title": "Align assignment location with address"
  },
  {
    "number": 163,
    "date": "2026-08-25",
    "commit": "13ede4c",
    "title": "Keep address visible beside location fields"
  },
  {
    "number": 164,
    "date": "2026-08-25",
    "commit": "bc38919",
    "title": "Compact new-loan assignment report"
  },
  {
    "number": 165,
    "date": "2026-08-25",
    "commit": "5aa9fbe",
    "title": "Remove duplicate officer location map button"
  },
  {
    "number": 166,
    "date": "2026-08-25",
    "commit": "bc40615",
    "title": "Add persistent maps and draggable schedules"
  },
  {
    "number": 167,
    "date": "2026-08-25",
    "commit": "345a7bb",
    "title": "Disable VPS webpack build worker"
  },
  {
    "number": 168,
    "date": "2026-08-25",
    "commit": "29008b5",
    "title": "Add scoped location map links"
  },
  {
    "number": 169,
    "date": "2026-08-25",
    "commit": "56dcdd7",
    "title": "Add optional client address pins"
  },
  {
    "number": 170,
    "date": "2026-08-27",
    "commit": "5f7e864",
    "title": "Let admins pin a barangay from their current location"
  },
  {
    "number": 171,
    "date": "2026-08-27",
    "commit": "cd3b82a",
    "title": "Scope new-loan assignment to the assigner's own team"
  },
  {
    "number": 172,
    "date": "2026-08-27",
    "commit": "4c33a98",
    "title": "Restore the Branch summary button on officer pivot rows",
    "request": "add branch button after the location, we already have it before just put it back."
  },
  {
    "number": 173,
    "date": "2026-08-27",
    "commit": "a1615f5",
    "title": "Narrow location fields to cascading masterlist dropdowns",
    "request": "make the image2 province, city/municipality and barangay to be the same in image1 so that when you select a province it will only display the city/municipality of that province ang display only the barangay of the selected city/municipality - do this to all layouts with fields."
  },
  {
    "number": 174,
    "date": "2026-08-28",
    "commit": "6b4f6f8",
    "title": "Lead the tagging filters with a wider Customer name",
    "request": "move the customer name as the first filter and makeit more wider, adjust the filter field size appropriately"
  },
  {
    "number": 175,
    "date": "2026-08-28",
    "commit": "4b5666c",
    "title": "Correct the VPS backup path and retention in the docs",
    "request": "yes fix those path and deploy when done"
  },
  {
    "number": 176,
    "date": "2026-08-28",
    "commit": "b0adaa8",
    "title": "Show navigation progress as a top bar instead of dimming the page",
    "request": "replace this with progress bar don't dim the screen"
  },
  {
    "number": 177,
    "date": "2026-08-28",
    "commit": "320e314",
    "title": "Open loan details from team-leader rows and filter them by column",
    "request": "clicking the quantities should show the loan details just like in the totals, and when inside the loan details add a search filter. the first search is the column label and the second is the value of the column label i want to search. do this to all loan details list in this pivot."
  },
  {
    "number": 178,
    "date": "2026-08-28",
    "commit": "a0f7f63",
    "title": "Open loan details from every Location Pivot and Zone Summary row",
    "request": "can you do that latest instruction to layout of these images. [Location Pivot and Zone Summary]"
  },
  {
    "number": 179,
    "date": "2026-08-28",
    "commit": "97f5786",
    "title": "Add an administrator change log under Settings",
    "request": "can you recall all of my prompts and summary of your actions and put it in this app, number it and date so that i can view it - only for admin account you can put it inside the setting menu item."
  },
  {
    "number": 180,
    "date": "2026-08-28",
    "commit": "4f8d865",
    "title": "Record the latest changes in the change log"
  },
  {
    "number": 181,
    "date": "2026-08-28",
    "commit": "feec0f7",
    "title": "Add loan verification and invalid-address re-tagging",
    "request": "create a submenu put it under Taggings call it Verify Loans, summary by branch no. of loans and principal balance in a card [...] Make a menu call it Verfied Loans [...] The account to do this will have a privilege of Bookkeeper. / put nos. on the clients and the column labels make it toggle sort asc desc, pagination first,prev,next,last. / can we add a field not_valid_address to all loans with balance [...] call it Invalid address [...] Area TL, Branch TL and Bookkeeper has access to this."
  }
];
