// Regenerates lib/change-log-data.ts from the git history.
//
// The viewer reads a committed data file rather than shelling out to git at runtime. This
// VPS cannot reliably reap child processes - the same fault that hangs `next build` and the
// pm2 daemon - so spawning git from a page request would eventually hang that request.
// Generating at development time keeps the page a plain read.
//
// Run after adding commits, before deploying:
//   npm run changelog:generate

import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import path from "node:path";

// Requests captured from the working sessions. Older entries carry their commit subject
// only - the conversation that produced them was not recorded at the time.
const REQUESTS: Record<string, string> = {
  "4c33a98": "add branch button after the location, we already have it before just put it back.",
  a1615f5: "make the image2 province, city/municipality and barangay to be the same in image1 so that when you select a province it will only display the city/municipality of that province ang display only the barangay of the selected city/municipality - do this to all layouts with fields.",
  "6b4f6f8": "move the customer name as the first filter and makeit more wider, adjust the filter field size appropriately",
  "4b5666c": "yes fix those path and deploy when done",
  b0adaa8: "replace this with progress bar don't dim the screen",
  "320e314": "clicking the quantities should show the loan details just like in the totals, and when inside the loan details add a search filter. the first search is the column label and the second is the value of the column label i want to search. do this to all loan details list in this pivot.",
  a0f7f63: "can you do that latest instruction to layout of these images. [Location Pivot and Zone Summary]",
  "97f5786": "can you recall all of my prompts and summary of your actions and put it in this app, number it and date so that i can view it - only for admin account you can put it inside the setting menu item.",
  feec0f7: "create a submenu put it under Taggings call it Verify Loans, summary by branch no. of loans and principal balance in a card [...] Make a menu call it Verfied Loans [...] The account to do this will have a privilege of Bookkeeper. / put nos. on the clients and the column labels make it toggle sort asc desc, pagination first,prev,next,last. / can we add a field not_valid_address to all loans with balance [...] call it Invalid address [...] Area TL, Branch TL and Bookkeeper has access to this."
};

function gitLog() {
  const raw = execFileSync("git", ["log", "--reverse", "--date=short", "--pretty=format:%ad\x1f%h\x1f%s"], {
    cwd: path.join(__dirname, ".."),
    encoding: "utf8",
    maxBuffer: 20 * 1024 * 1024
  });
  return raw.split("\n").filter(Boolean).map((line, index) => {
    const [date, commit, title] = line.split("\x1f");
    return { number: index + 1, date, commit, title, request: REQUESTS[commit] };
  });
}

const entries = gitLog();
const file = `// Generated by scripts/generate-change-log.ts - do not edit by hand.
// Regenerate with: npm run changelog:generate

import type { ChangeLogEntry } from "@/lib/change-log";

export const CHANGE_LOG: ChangeLogEntry[] = ${JSON.stringify(entries, null, 2)};
`;

const target = path.join(__dirname, "..", "lib", "change-log-data.ts");
writeFileSync(target, file, "utf8");
console.log(`Wrote ${entries.length} change log entries to ${target}`);
